name: Publish teenstudy to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish teenstudy to PyPI and TestPyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.0

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/

    - name: Publish teenstudy to Test PyPI
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        password: ${{ secrets.TEST_PUBLISH_TEENSTUDY }}
        repository_url: https://test.pypi.org/legacy/
        
    - name: Publish teenstudy to PyPI
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        password: ${{ secrets.PUBLISH_TEENSTUDY }}
